//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Shopinfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Shopinfo.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReviews", ReplyAction="http://tempuri.org/IService1/GetReviewsResponse")]
        string[] GetReviews(string storename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReviews", ReplyAction="http://tempuri.org/IService1/GetReviewsResponse")]
        System.Threading.Tasks.Task<string[]> GetReviewsAsync(string storename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseInfo", ReplyAction="http://tempuri.org/IService1/GetBaseInfoResponse")]
        System.Collections.Generic.Dictionary<string, string> GetBaseInfo(string storename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseInfo", ReplyAction="http://tempuri.org/IService1/GetBaseInfoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBaseInfoAsync(string storename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : web.Shopinfo.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<web.Shopinfo.IService1>, web.Shopinfo.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetReviews(string storename) {
            return base.Channel.GetReviews(storename);
        }
        
        public System.Threading.Tasks.Task<string[]> GetReviewsAsync(string storename) {
            return base.Channel.GetReviewsAsync(storename);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetBaseInfo(string storename) {
            return base.Channel.GetBaseInfo(storename);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBaseInfoAsync(string storename) {
            return base.Channel.GetBaseInfoAsync(storename);
        }
    }
}
