//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.XML_Ref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML_Ref.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xml_verify", ReplyAction="http://tempuri.org/IService1/xml_verifyResponse")]
        string[] xml_verify(string xml_url, string xsd_url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xml_verify", ReplyAction="http://tempuri.org/IService1/xml_verifyResponse")]
        System.Threading.Tasks.Task<string[]> xml_verifyAsync(string xml_url, string xsd_url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpthserach", ReplyAction="http://tempuri.org/IService1/xpthserachResponse")]
        string[] xpthserach(string xml_url, string xpath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpthserach", ReplyAction="http://tempuri.org/IService1/xpthserachResponse")]
        System.Threading.Tasks.Task<string[]> xpthserachAsync(string xml_url, string xpath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryIt.XML_Ref.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryIt.XML_Ref.IService1>, TryIt.XML_Ref.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] xml_verify(string xml_url, string xsd_url) {
            return base.Channel.xml_verify(xml_url, xsd_url);
        }
        
        public System.Threading.Tasks.Task<string[]> xml_verifyAsync(string xml_url, string xsd_url) {
            return base.Channel.xml_verifyAsync(xml_url, xsd_url);
        }
        
        public string[] xpthserach(string xml_url, string xpath) {
            return base.Channel.xpthserach(xml_url, xpath);
        }
        
        public System.Threading.Tasks.Task<string[]> xpthserachAsync(string xml_url, string xpath) {
            return base.Channel.xpthserachAsync(xml_url, xpath);
        }
    }
}
